### ISSUE TITLE
Description of how to get started

### ISSUE THREAD

**Issue by AmkeNimm** [apeck12/sfx_utils#15]
Add information on how to get the ssh key, get started with the jupyter hub and use the right kernel

**Comment by apeck12** [comment]
@AmkeNimm, sorry -- this was my oversight for not merging the Wikis from the two forks. There's a description for how to get started here: https://github.com/lcls-users/sfx/wiki/Get-started. It doesn't have information on how to get the ssh key though, so if you wouldn't mind adding that, we'd appreciate it! I'll try to get the Wikis synced soon.

**Comment by apeck12** [comment]
@AmkeNimm, thanks for adding the note about ssh keys!
