### ISSUE TITLE
Adding the option to compute a powder over the whole run

### ISSUE THREAD

**Issue by fredericpoitevin** [apeck12/sfx_utils#2]
It might be useful to add an option to set `n_images` here so that it goes over all images in the run: https://github.com/apeck12/sfx_utils/blob/main/sfx_utils/geom_opt.py#L41

Maybe `n_images=-1`?

**Comment by fredericpoitevin** [comment]
@apeck12 I believe this has been addressed by #6 , right? Should we close it?

**Comment by apeck12** [comment]
You're right -- thanks for catching that, @fredericpoitevin!
