### ISSUE TITLE
Diagnostic statistics per-run

### ISSUE THREAD

**Issue by apeck12** [apeck12/sfx_utils#4]
We'd like to pull out the following statistics per event and plot their trajectory over the course of a given run:
- total intensity
- minimum intensity
- maximum intensity
- median intensity
By default, we assume that we're examining the calibrated images.

**Comment by apeck12** [comment]
@fredericpoitevin, for the above stats, should we ignore pixels that are masked by detector calibration? And if so, do you know if using psana to retrieve the calibrated images (`detector.calib(evt=evt)`) will result in masked pixels having a value of 0? Or is there another way to retrieve just the mask? Sorry -- super rusty on my psana know-how...

**Comment by fredericpoitevin** [comment]
Sorry @apeck12 I missed this one!

That's a good question...I believe the Detector class is the proper way to access pixel status, and hence mask, but I'd have to refresh my memories about how that's done exactly. It looks like there must be a way to access it though: https://github.com/lcls-psana/Detector/blob/master/src/AreaDetector.py#L636

**Comment by apeck12** [comment]
Thanks, @fredericpoitevin! I realized it didn't actually make sense for what I was trying to do, but I'll keep that in mind for the future.
